### ISSUE TITLE
是否考虑做一下平衡？

### ISSUE THREAD

**Issue by Flithor** [Crapsky233/OverpoweredGoldDust#1]
金矿->金锭->金尘->+石头->金矿
这直接可以无限增值了，过于imba

建议加一点和魔法有关的东西进去
比如改为在魔法球处制作，需要使用一些boss掉落物或者魔法师出售的特别的物品

**Comment by Cyrillya** [comment]
我做这个Mod也没怎么考虑平衡，就图一乐，因为就算去掉了合成配方，原版肉后商人也会17银卖一个金尘，还是可以无限增值（

**Comment by Cyrillya** [comment]
做了一些小平衡，至少现在要五个星星
